apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam2025
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exam2025
  template:
    metadata:
      labels:
        app: exam2025
    spec:
      containers:
      - name: exam2025
        image: gcr.io/icai2025/exam2025:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: GCP_BUCKET_NAME
          value: "REPLACE_BUCKET_NAME"
        livenessProbe:
          httpGet:
            path: /probe
            port: 5001
          periodSeconds: 2
          initialDelaySeconds: 5
